#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mservice
    username: postgres
    password: postgres  # Ensure you provide the correct password or remove if not needed
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: TICKETING-SERVICE
  #config:
   # import: optional:configserver:http://localhost:9296